vehicle_baseとCylinder partsの追加
IRSL-tut/robot_assembler_plugin pull request #61
Opened 2023-02-21 08:34 UTC by Hiroaki-Masuzawa

#54 に関連．

プラグとソケットを両面に配置したvehicle_baseと上下をつなぐCylinder partsを追加．

2023-02-21 09:40 UTC, Hiroaki-Masuzawa commented
@lighthouse117 descriptionの記載内容確認してもらえると助かります．

2023-02-21 09:57 UTC, lighthouse117 requested changes

2023-02-21 09:57 UTC, tomosii commented on config/irsl/irsl_assembler_config.yaml
> +    class: Base plate (Double plag)
正しいスペルは "plug" でしょうか。

2023-02-21 09:57 UTC, tomosii commented on config/irsl/irsl_assembler_config.yaml
> +    description: Base plate for vehicles with LEGO plugs on both sides
両面プラグであるという説明のままになっているため、以下の修正案はいかがでしょうか。

```suggestion
    description: Base plate for vehicles with LEGO plugs and sockets on each side.
```

2023-02-21 09:58 UTC, lighthouse117 commented
@Hiroaki-Masuzawa 
ご確認をよろしくお願いいたします。

2023-02-21 10:07 UTC, YoheiKakiuchi commented
すくなくともcylinderはblockと同じだから入れる必要ないように思う。
実機になにを使うかは別として。

2023-02-22 01:52 UTC, Hiroaki-Masuzawa commented on config/irsl/irsl_assembler_config.yaml
> +    class: Base plate (Double plag)
スペルミスです．修正します．

2023-02-22 01:52 UTC, Hiroaki-Masuzawa commented on config/irsl/irsl_assembler_config.yaml
> +    description: Base plate for vehicles with LEGO plugs on both sides
記載修正します．

2023-02-22 02:03 UTC, Hiroaki-Masuzawa commented
@YoheiKakiuchi 
cylinderは外しました．
おっしゃる通りcylinderの機能は同一高さのblockと同じなので機能設計には不要かと思います．今後のデータ作成方針として同一の機能設計が他パーツでできる場合には追加しない方針とします．

2023-03-02 02:00 UTC, Hiroaki-Masuzawa commented
@lighthouse117 
修正済みですので確認をお願いします．

2023-03-02 06:05 UTC, lighthouse117 requested changes

2023-03-02 06:05 UTC, lighthouse117 commented on config/irsl/irsl_assembler_config.yaml
> +    class: Base plate (Plag and socket)
@Hiroaki-Masuzawa
こちらのPlugのスペルの修正もお願いできますでしょうか。🙇

```suggestion
    class: Base plate (Plug and socket)
```

2023-03-02 06:45 UTC, Hiroaki-Masuzawa commented on config/irsl/irsl_assembler_config.yaml
> +    class: Base plate (Plag and socket)
先ほど修正しました．

2023-03-02 07:09 UTC, lighthouse117 approved these changes
LGTM!

2023-03-03 03:41 UTC, merged